### ISSUE TITLE
tablePollingInterval config in `limits.json` is applied in an unexpected way

### ISSUE THREAD

**Issue by showeimer** [kui-shell/AnimalApp#279] opened 2020-01-24 18:30 UTC
https://github.com/kui-shell/plugin-kubeui/blob/master/plugins/plugin-kubeui/src/controller/kubectl/status.ts#L233

We are permitted to set a `tablePollingInterval` in our `client.d/limits.json` however; the actual application of that configuration is not what is expected.  Link above shows code that this configuration is actually to set the maximum polling interval.  As a developer working on a KUI client, I would expect that this configuration sets the actual polling interval.

**Comment by starpit** [comment] 2020-01-24 18:44
we poll a few times more quickly, but within a few seconds, we arrive at the steady state. this is by design, so that the user doesn't wait 5 or more seconds to see that a pod creation finished. once we port the create/delete/apply to use push (right now, they're still using polling), this will go away entirely, so i'm inclined to close this was as working as designed?

**Comment by showeimer** [comment] 2020-01-24 19:04
@starpit that sounds interesting.  Is that push only for electron or does that also work with browser push notification apis?

**Comment by starpit** [comment] 2020-01-24 19:08
we have switched the `kubectl get <kind> --watch` implementation so that it avoids polling altogether. this relies on the underlying kubectl support for pushing updates as they occur (the kube apiserver supports this).

however, for create/delete/apply, kubectl does not directly support this, so we are being cautious, and have continued to use polling to support those use cases.

but it does seem like a good possibilty that we can switch the create/delete/apply to use the same  strategy as we already use for `get --watch`. it requires more thought, given that this use case is not directly supported by `kubectl`.

for example, i may issue `create -f <directory>`; kubectl does not support `get --watch -f <dir>` on a directory; indeed, `get --watch -f` is quite limited right now in what it can support. e.g. you cannot even do a `get --watch -f <file>` if the file contains a heterogeneous collection of resource kinds.

**Closed** 2021-09-09 22:36 UTC
